spring.application.name=gms-mvp

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/gms
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=3600000

app.default-superadmin.username=superadmin
app.default-superadmin.email=superadmin@gms.local
app.default-superadmin.password=superadmin123
